language: python
sudo: false
cache: pip

matrix:
  include:
    - python: 3.6

install:
  - pip install "pip>=7.1.0"
  - pip install pyglet pytest pyinstaller importlib_resources

script:
  - python -m pytest -vv test_dama/
  - pyinstaller __main__.py -n dama-game
      --exclude-module tkinter
      --add-data dama/resources:dama/resources
      -F -w
